import React, {Component} from 'react';
import { Container, Header, Left, Body, Right, Button, Title, Text } from 'native-base';
import Icon from 'react-native-vector-icons/FontAwesome';


class Home extends Component {
  componentWillMount(){
    var PushNotification = require('react-native-push-notification');

    PushNotification.localNotification({
    /* Android Only Properties */
    id: '0', // (optional) Valid unique 32 bit integer specified as string. default: Autogenerated Unique ID
    ticker: "My Notification Ticker", // (optional)
    autoCancel: true, // (optional) default: true
    largeIcon: "ic_launcher", // (optional) default: "ic_launcher"
    smallIcon: "ic_notification", // (optional) default: "ic_notification" with fallback for "ic_launcher"
    subText: "Don't forget me!", // (optional) default: none
    color: "red", // (optional) default: system default
    vibrate: true, // (optional) default: true
    vibration: 300, // vibration length in milliseconds, ignored if vibrate=false, default: 1000
    tag: 'some_tag', // (optional) add tag to message
    group: "group", // (optional) add group to message
    ongoing: false, // (optional) set whether this is an "ongoing" notification
    priority: "high", // (optional) set notification priority, default: high
    visibility: "private", // (optional) set notification visibility, default: private
    importance: "high", // (optional) set notification importance, default: high

    /* iOS and Android properties */
    title: "Learn French", // (optional)
    message: "New French Word!", // (required)
});

  }
  render () {
    return (
      <Container>
        <Header>
          <Left>
            <Button transparent>
              <Icon name='bars' color="white" />
            </Button>
          </Left>
          <Body>
            <Title>Home</Title>
          </Body>

        </Header>
      </Container>
    );
  }
}

export default Home;
